name: auth
description: Authentication Service
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  conduit: ^4.0.1
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
